# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import audio_pb2 as audio__pb2


class AudioStreamerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStream = channel.unary_stream(
                '/rero.AudioStreamer/GetStream',
                request_serializer=audio__pb2.StreamRequest.SerializeToString,
                response_deserializer=audio__pb2.Audio.FromString,
                )


class AudioStreamerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetStream(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AudioStreamerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GetStream,
                    request_deserializer=audio__pb2.StreamRequest.FromString,
                    response_serializer=audio__pb2.Audio.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rero.AudioStreamer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AudioStreamer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/rero.AudioStreamer/GetStream',
            audio__pb2.StreamRequest.SerializeToString,
            audio__pb2.Audio.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
