# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: speech_recognition.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import audio_pb2 as audio__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18speech_recognition.proto\x12\x04rero\x1a\x0b\x61udio.proto\")\n\x17SpeechRecognitionResult\x12\x0e\n\x06result\x18\x01 \x01(\t\"\x1d\n\x0bVocabResult\x12\x0e\n\x06result\x18\x01 \x01(\t\"\x16\n\x05Vocab\x12\r\n\x05vocab\x18\x01 \x01(\t2\x84\x01\n\x11SpeechRecognition\x12\x41\n\x0fRecognizeSpeech\x12\x0b.rero.Audio\x1a\x1d.rero.SpeechRecognitionResult\"\x00(\x01\x12,\n\x08SetVocab\x12\x0b.rero.Vocab\x1a\x11.rero.VocabResult\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'speech_recognition_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SPEECHRECOGNITIONRESULT._serialized_start=47
  _SPEECHRECOGNITIONRESULT._serialized_end=88
  _VOCABRESULT._serialized_start=90
  _VOCABRESULT._serialized_end=119
  _VOCAB._serialized_start=121
  _VOCAB._serialized_end=143
  _SPEECHRECOGNITION._serialized_start=146
  _SPEECHRECOGNITION._serialized_end=278
# @@protoc_insertion_point(module_scope)
