# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: speech_recognition.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import audio_pb2 as audio__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='speech_recognition.proto',
  package='rero',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18speech_recognition.proto\x12\x04rero\x1a\x0b\x61udio.proto\")\n\x17SpeechRecognitionResult\x12\x0e\n\x06result\x18\x01 \x01(\t2V\n\x11SpeechRecognition\x12\x41\n\x0fRecognizeSpeech\x12\x0b.rero.Audio\x1a\x1d.rero.SpeechRecognitionResult\"\x00(\x01\x62\x06proto3'
  ,
  dependencies=[audio__pb2.DESCRIPTOR,])




_SPEECHRECOGNITIONRESULT = _descriptor.Descriptor(
  name='SpeechRecognitionResult',
  full_name='rero.SpeechRecognitionResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='rero.SpeechRecognitionResult.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=88,
)

DESCRIPTOR.message_types_by_name['SpeechRecognitionResult'] = _SPEECHRECOGNITIONRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SpeechRecognitionResult = _reflection.GeneratedProtocolMessageType('SpeechRecognitionResult', (_message.Message,), {
  'DESCRIPTOR' : _SPEECHRECOGNITIONRESULT,
  '__module__' : 'speech_recognition_pb2'
  # @@protoc_insertion_point(class_scope:rero.SpeechRecognitionResult)
  })
_sym_db.RegisterMessage(SpeechRecognitionResult)



_SPEECHRECOGNITION = _descriptor.ServiceDescriptor(
  name='SpeechRecognition',
  full_name='rero.SpeechRecognition',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=90,
  serialized_end=176,
  methods=[
  _descriptor.MethodDescriptor(
    name='RecognizeSpeech',
    full_name='rero.SpeechRecognition.RecognizeSpeech',
    index=0,
    containing_service=None,
    input_type=audio__pb2._AUDIO,
    output_type=_SPEECHRECOGNITIONRESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SPEECHRECOGNITION)

DESCRIPTOR.services_by_name['SpeechRecognition'] = _SPEECHRECOGNITION

# @@protoc_insertion_point(module_scope)
